// Generated by Scripts/generate_extended_materials.py.
import Foundation

struct EffectControl {
    let name: String
    let label: String
    let range: ClosedRange<Float>
    let value: Float
}

extension OpticsEffect {
    var additionalControls: [EffectControl] {
        switch self {
        case .catEye: return [
            .init(name: "Sharpness", label: "亮带锐度", range: 12...180, value: 70),
            .init(name: "AxisAngle", label: "纤维方向（°）", range: 0...180, value: 0),
            .init(name: "LightAngle", label: "光源方位（°）", range: -90...90, value: 18),
            .init(name: "Gain", label: "亮度", range: 0.2...3, value: 1),
        ]
        case .starGem: return [
            .init(name: "Sharpness", label: "星芒锐度", range: 12...180, value: 90),
            .init(name: "AxisAngle", label: "星芒方向（°）", range: 0...180, value: 0),
            .init(name: "LightAngle", label: "光源方位（°）", range: -90...90, value: 18),
            .init(name: "Gain", label: "亮度", range: 0.2...3, value: 1),
        ]
        case .moonstone: return [
            .init(name: "Softness", label: "柔光集中度", range: 1...12, value: 3),
            .init(name: "Depth", label: "内部层次", range: 0...1, value: 0.55),
            .init(name: "LightAngle", label: "光源方位（°）", range: -90...90, value: 18),
            .init(name: "Gain", label: "亮度", range: 0.2...3, value: 1),
        ]
        case .labradorite: return [
            .init(name: "Spacing", label: "等效层厚（nm）", range: 100...550, value: 190),
            .init(name: "DomainScale", label: "晶域尺度", range: 2...18, value: 6),
            .init(name: "Sharpness", label: "闪光集中度", range: 2...50, value: 12),
            .init(name: "LightAngle", label: "光源方位（°）", range: -90...90, value: 18),
            .init(name: "Gain", label: "亮度", range: 0.2...3, value: 1),
        ]
        case .sunstone: return [
            .init(name: "GrainScale", label: "包裹体密度", range: 20...120, value: 55),
            .init(name: "Threshold", label: "闪点稀疏度", range: 0.5...0.95, value: 0.83),
            .init(name: "Sharpness", label: "闪点锐度", range: 8...100, value: 35),
            .init(name: "LightAngle", label: "光源方位（°）", range: -90...90, value: 18),
            .init(name: "Gain", label: "亮度", range: 0.2...3, value: 1),
        ]
        case .alexandrite: return [
            .init(name: "Illuminant", label: "参考照明：日光 → 暖光", range: 0...1, value: 0),
            .init(name: "PathLength", label: "吸收光程", range: 0.3...3, value: 1),
            .init(name: "Gain", label: "亮度", range: 0.2...3, value: 1),
        ]
        case .pleochroism: return [
            .init(name: "PathLength", label: "吸收光程", range: 0.3...3, value: 1),
            .init(name: "AxisAngle", label: "晶轴方向（°）", range: 0...180, value: 0),
            .init(name: "AxisTilt", label: "晶轴倾角（°）", range: 0...90, value: 0),
            .init(name: "Gain", label: "亮度", range: 0.2...3, value: 1),
        ]
        case .retroreflective: return [
            .init(name: "LightAngle", label: "光源偏离视线基准（°）", range: -60...60, value: 0),
            .init(name: "Sharpness", label: "回归光束集中度", range: 20...500, value: 160),
            .init(name: "Gain", label: "亮度", range: 0.2...3, value: 1),
        ]
        case .oilFilm: return [
            .init(name: "Thickness", label: "平均膜厚（nm）", range: 0...1000, value: 380),
            .init(name: "Variation", label: "膜厚变化（nm）", range: 0...400, value: 180),
            .init(name: "Gain", label: "亮度", range: 0.2...3, value: 1),
        ]
        case .titanium: return [
            .init(name: "Thickness", label: "氧化层厚度（nm）", range: 0...300, value: 75),
            .init(name: "Variation", label: "厚度变化（nm）", range: 0...100, value: 12),
            .init(name: "Gain", label: "亮度", range: 0.2...3, value: 1),
        ]
        case .lensCoating: return [
            .init(name: "Thickness", label: "MgF₂ 厚度（nm）", range: 0...300, value: 100),
            .init(name: "Variation", label: "厚度变化（nm）", range: 0...100, value: 0),
            .init(name: "Gain", label: "反射显示增益", range: 1...15, value: 6),
        ]
        case .dichroic: return [
            .init(name: "Thickness", label: "设计中心波长（nm）", range: 400...700, value: 540),
            .init(name: "Variation", label: "中心波长变化（nm）", range: 0...100, value: 0),
            .init(name: "Transmission", label: "显示通道：反射 → 透射", range: 0...1, value: 0),
            .init(name: "Gain", label: "亮度", range: 0.2...3, value: 1),
        ]
        default: return []
        }
    }
}
