// Generated by Scripts/generate_extended_materials.py.
import Foundation

struct EffectControl {
    let name: String
    let label: String
    let range: ClosedRange<Float>
    let value: Float
}

extension OpticsEffect {
    var additionalControls: [EffectControl] {
        switch self {
        case .catEye: return [
            .init(name: "Sharpness", label: "亮带锐度", range: 12...180, value: 70),
            .init(name: "AxisAngle", label: "纤维方向（°）", range: 0...180, value: 0),
            .init(name: "LightAngle", label: "光源方位（°）", range: -90...90, value: 18),
            .init(name: "Gain", label: "亮度", range: 0.2...3, value: 1),
        ]
        case .starGem: return [
            .init(name: "Sharpness", label: "星芒锐度", range: 12...180, value: 90),
            .init(name: "AxisAngle", label: "星芒方向（°）", range: 0...180, value: 0),
            .init(name: "LightAngle", label: "光源方位（°）", range: -90...90, value: 18),
            .init(name: "Gain", label: "亮度", range: 0.2...3, value: 1),
        ]
        case .moonstone: return [
            .init(name: "Softness", label: "柔光集中度", range: 1...12, value: 3),
            .init(name: "Depth", label: "内部层次", range: 0...1, value: 0.55),
            .init(name: "LightAngle", label: "光源方位（°）", range: -90...90, value: 18),
            .init(name: "Gain", label: "亮度", range: 0.2...3, value: 1),
        ]
        case .labradorite: return [
            .init(name: "Spacing", label: "等效层厚（nm）", range: 100...550, value: 190),
            .init(name: "DomainScale", label: "晶域尺度", range: 2...18, value: 6),
            .init(name: "Sharpness", label: "闪光集中度", range: 2...50, value: 12),
            .init(name: "LightAngle", label: "光源方位（°）", range: -90...90, value: 18),
            .init(name: "Gain", label: "亮度", range: 0.2...3, value: 1),
        ]
        case .sunstone: return [
            .init(name: "GrainScale", label: "包裹体密度", range: 20...120, value: 55),
            .init(name: "Threshold", label: "闪点稀疏度", range: 0.5...0.95, value: 0.83),
            .init(name: "Sharpness", label: "闪点锐度", range: 8...100, value: 35),
            .init(name: "LightAngle", label: "光源方位（°）", range: -90...90, value: 18),
            .init(name: "Gain", label: "亮度", range: 0.2...3, value: 1),
        ]
        case .alexandrite: return [
            .init(name: "Illuminant", label: "参考照明：日光 → 暖光", range: 0...1, value: 0),
            .init(name: "PathLength", label: "吸收光程", range: 0.3...3, value: 1),
            .init(name: "Gain", label: "亮度", range: 0.2...3, value: 1),
        ]
        case .pleochroism: return [
            .init(name: "PathLength", label: "吸收光程", range: 0.3...3, value: 1),
            .init(name: "AxisAngle", label: "晶轴方向（°）", range: 0...180, value: 0),
            .init(name: "AxisTilt", label: "晶轴倾角（°）", range: 0...90, value: 0),
            .init(name: "Gain", label: "亮度", range: 0.2...3, value: 1),
        ]
        case .retroreflective: return [
            .init(name: "LightAngle", label: "光源偏离视线基准（°）", range: -60...60, value: 0),
            .init(name: "Sharpness", label: "回归光束集中度", range: 20...500, value: 160),
            .init(name: "Gain", label: "亮度", range: 0.2...3, value: 1),
        ]
        case .oilFilm: return [
            .init(name: "Thickness", label: "平均膜厚（nm）", range: 0...1000, value: 380),
            .init(name: "Variation", label: "膜厚变化（nm）", range: 0...400, value: 180),
            .init(name: "Gain", label: "亮度", range: 0.2...3, value: 1),
        ]
        case .titanium: return [
            .init(name: "Thickness", label: "氧化层厚度（nm）", range: 0...300, value: 75),
            .init(name: "Variation", label: "厚度变化（nm）", range: 0...100, value: 12),
            .init(name: "Gain", label: "亮度", range: 0.2...3, value: 1),
        ]
        case .lensCoating: return [
            .init(name: "Thickness", label: "MgF₂ 厚度（nm）", range: 0...300, value: 100),
            .init(name: "Variation", label: "厚度变化（nm）", range: 0...100, value: 0),
            .init(name: "Gain", label: "反射显示增益", range: 1...15, value: 6),
        ]
        case .dichroic: return [
            .init(name: "Thickness", label: "设计中心波长（nm）", range: 400...700, value: 540),
            .init(name: "Variation", label: "中心波长变化（nm）", range: 0...100, value: 0),
            .init(name: "Transmission", label: "显示通道：反射 → 透射", range: 0...1, value: 0),
            .init(name: "Gain", label: "亮度", range: 0.2...3, value: 1),
        ]
        case .gemFire: return [
            .init(name: "FacetScale", label: "切面密度", range: 3...18, value: 8),
            .init(name: "CutStrength", label: "切面倾角", range: 0...1, value: 0.55),
            .init(name: "Dispersion", label: "色散强度", range: 0...0.25, value: 0.16),
            .init(name: "InternalMix", label: "内部反射", range: 0...1, value: 0.65),
            .init(name: "Gain", label: "亮度", range: 0.2...3, value: 1.2),
        ]
        case .absorbingGlass: return [
            .init(name: "Thickness", label: "吸收厚度", range: 0...3, value: 0.85),
            .init(name: "Tint", label: "吸收配色：青 → 琥珀", range: 0...1, value: 0.25),
            .init(name: "Refraction", label: "折射率", range: 1...1.8, value: 1.5),
            .init(name: "Gain", label: "亮度", range: 0.2...3, value: 1.2),
        ]
        case .lenticular: return [
            .init(name: "ViewSpread", label: "视角切换灵敏度", range: 0.3...2, value: 1),
            .init(name: "LensPitch", label: "柱镜条纹密度", range: 12...90, value: 42),
            .init(name: "BlendWidth", label: "视图过渡宽度", range: 0.05...0.9, value: 0.22),
            .init(name: "Gain", label: "亮度", range: 0.2...3, value: 1.2),
        ]
        case .moire: return [
            .init(name: "Frequency", label: "条纹密度", range: 6...55, value: 24),
            .init(name: "Mismatch", label: "双层频率差", range: 0.01...0.18, value: 0.055),
            .init(name: "LayerGap", label: "层间视差", range: 0...0.25, value: 0.1),
            .init(name: "Rotation", label: "第二层旋角（°）", range: 0...25, value: 5),
            .init(name: "Gain", label: "亮度", range: 0.2...3, value: 1.2),
        ]
        case .parallaxNebula: return [
            .init(name: "Depth", label: "内部深度", range: 0...0.65, value: 0.35),
            .init(name: "Scale", label: "云层尺度", range: 0.4...1.4, value: 0.85),
            .init(name: "Density", label: "云层遮挡", range: 0...1, value: 0.65),
            .init(name: "Gain", label: "亮度", range: 0.2...4, value: 1.6),
        ]
        case .rainbow: return [
            .init(name: "LightAngle", label: "光源方位（°）", range: 90...180, value: 138),
            .init(name: "Width", label: "虹带展宽（°）", range: 0.2...1.4, value: 0.35),
            .init(name: "Gain", label: "亮度", range: 0.2...6, value: 3),
        ]
        case .atmosphere: return [
            .init(name: "LightAngle", label: "太阳方位（°）", range: 0...180, value: 70),
            .init(name: "Density", label: "大气光学厚度", range: 0.1...3, value: 1),
            .init(name: "Sunset", label: "日落偏移", range: -0.6...0.6, value: 0),
            .init(name: "Gain", label: "亮度", range: 0.2...6, value: 2.5),
        ]
        default: return []
        }
    }
}
